Update tutorial
kantacky/strayit-ios pull request #53
Opened 2024-05-12 11:53 UTC by inomeu

# Update
チュートリアル画面の実装

# Update Details
- チュートリアル画面の実装

# Confirmed
- エラーは出ないけど、多分エラー内容的に自分のXcodeの問題でビルドができない、、

# UI Difference
|BEFORE|AFTER|
|:--:|:--:|
|<img width="300" src=""/>|<img width="300" src=""/>|

2024-05-12 12:13 UTC, kantacky requested changes
ぱっと見た感じの雑なコメントです...

2024-05-12 12:13 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITTutorial/TutorialPage0.swift
> +                .padding(3)
![review-must](https://img.shields.io/badge/review-must-red.svg)
Vertical方向のpaddingは、VStackがネストしてもいいから、VStackのspacingで調整するようにしよう
Horizontal方向のpadding一番外側のVStackにまとめてかけよう

2024-05-12 12:13 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITTutorial/TutorialPage1.swift
> +                    .frame(width: 175, height: 175)
![review-must](https://img.shields.io/badge/review-must-red.svg)
175...?? 4の倍数で！172とか??

2024-05-12 12:13 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITTutorial/TutorialPage1.swift
> +                    )
![review-imo](https://img.shields.io/badge/review-imo-orange.svg)
ここだけ別Viewに切り出したい感

2024-05-12 12:13 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITTutorial/TutorialPage1.swift
> +                    .frame(width: 175, height: 175)
![review-imo](https://img.shields.io/badge/review-imo-orange.svg)
.containerRelativeFrameで、画面幅の1/2とかにした方が綺麗かも？？
```suggestion
                Circle()
                    .stroke(
                        Color
                            .Semantic
                            .accent(.primary)
                            .color(colorScheme)
                    )
                    .containerRelativeFrame(.horizontal, span: 2, count: 1, spacing: 0)
```

2024-05-12 12:13 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITTutorial/TutorialPage2.swift
> +                .padding(3)
![review-must](https://img.shields.io/badge/review-must-red.svg)
4の倍数で！

2024-05-12 12:13 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITTutorial/TutorialPage3.swift
> +                .padding(3)
![review-must](https://img.shields.io/badge/review-must-red.svg)
4の倍数で！

2024-05-12 12:13 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITTutorial/TutorialView.swift
> +                .tag(3)
![review-must](https://img.shields.io/badge/review-must-red.svg)
最後のアクションは、TutorialViewに渡されるactionかな
```suggestion
                TutorialPage3(action: action)
                    .tag(3)
```

2024-05-12 12:13 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITTutorial/TutorialView.swift
> +            SliderIndicator(span: 4, count: selection)
![review-ask](https://img.shields.io/badge/review-ask-blue.svg)
ここだと、ボタンのしたに来ちゃうけど、いいのかな？？

2024-05-12 12:13 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITTutorial/TutorialView.swift
> +            SliderIndicator(span: 4, count: selection)
ボタンをさらにこの下に置いて、`selection`が最終ページの時だけ、ボタンのアクションを`self.action`にして、そうじゃない時は、`selection += 1`するみたいな感じでも良さそう

2024-05-12 12:13 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITTutorial/TutorialPage1.swift
> +                    .offset(x:50, y:0)
![review-ask](https://img.shields.io/badge/review-ask-blue.svg)
マジックナンバーすぎるなぁ
デバイスの大きさ変わるとどうなる？？
下の2つも同じく

2024-05-12 12:13 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITTutorial/Localizable.xcstrings
> +    "Allow notifications to be sent." : {
```suggestion
    "Allow app to send notifications" : {
```

2024-05-12 12:13 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITTutorial/Localizable.xcstrings
> +    "Allow the use of location information." : {
```suggestion
    "Allow app to use this device location" : {
```

2024-05-12 12:13 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITTutorial/Localizable.xcstrings
> +            "value" : "位置情報の送信を許可する"
```suggestion
            "value" : "位置情報の利用を許可する"
```

2024-05-12 12:13 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITTutorial/Localizable.xcstrings
> +    "Enjoy reaching your destination with three screens to choose from!" : {
```suggestion
    "Enjoy reaching your destination\nwith 3 types of screen!" : {
```

2024-05-13 00:35 UTC, inomeu commented on STRAYITPackage/Sources/STRAYITTutorial/TutorialPage1.swift
> +                    .frame(width: 175, height: 175)
これfigmaの丸のサイズに合わせたの〜でもどっちでもいいから変えとくね

2024-05-13 00:35 UTC, inomeu commented on STRAYITPackage/Sources/STRAYITTutorial/TutorialPage1.swift
> +                    )
たしかに、考えるよん

2024-05-13 00:51 UTC, inomeu commented on STRAYITPackage/Sources/STRAYITTutorial/TutorialPage2.swift
> +                .padding(3)
ここと一個下なんだけど、チュートリアル3つの画面で同じ位置に下のボタン置きたいのと文字とボタンの間隔をあけたくてとりあえず、テキストとボタンの間隔を全画面統一しようと思ってpadding置いてみたのね
なんかいい方法ないかな〜
とりあえず、paddingなくてもいいから消してみた

2024-05-13 00:55 UTC, inomeu commented on STRAYITPackage/Sources/STRAYITTutorial/TutorialPage1.swift
> +                    .offset(x:50, y:0)
まじでそうなの〜ボタンとテキストと画像の位置を要素ごと全画面の位置固定したいけど良い方法ある？

2024-05-13 00:55 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITTutorial/TutorialView.swift
> +            SliderIndicator(span: 4, count: selection)
ページをコンポーネント化するとかもありかも？？

2024-05-13 02:58 UTC, kantacky approved these changes
LGTM

2024-05-13 03:45 UTC, merged